/*
 * Created on 2026-05-01 ( 13:45:53 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.AdministrativoEntity;

/**
 * Spring Data JPA repository for the AdministrativoEntity entity.
 *
 * This interface extends {@link JpaRepository}, so it automatically inherits
 * standard persistence operations, including:
 * <ul>
 * <li>Create/update entities: {@link JpaRepository#save(Object)} and
 * {@link JpaRepository#saveAll(Iterable)}</li>
 * <li>Basic queries: {@link JpaRepository#findById(Object)},
 * {@link JpaRepository#findAll()}, and
 * {@link JpaRepository#getReferenceById(Object)}</li>
 * <li>Validation and counting: {@link JpaRepository#existsById(Object)} and
 * {@link JpaRepository#count()}</li>
 * <li>Deletion: {@link JpaRepository#deleteById(Object)},
 * {@link JpaRepository#delete(Object)}, and
 * {@link JpaRepository#deleteAll()}</li>
 * <li>Paging and sorting:
 * {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Pageable)}
 * and
 * {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Sort)}</li>
 * </ul>
 *
 * It can also be extended with derived query methods (findBy...),
 * following Spring Data JPA conventions.
 *
 * @category Repository
 * @version 1.0.0
 * @see JpaRepository
 * @see org.springframework.data.repository.CrudRepository
 * @see org.springframework.data.repository.PagingAndSortingRepository
 * @author a-cubica-r
 *
 */
@Repository
public interface AdministrativoRepository extends JpaRepository<AdministrativoEntity, Integer> {

	// Insert specific finders here

	// List<AdministrativoEntity> findByXxx(String xxx);

	// List<AdministrativoEntity> findByXxxStartingWith(String xxx);

	// List<AdministrativoEntity> findByXxxContaining(String xxx);

	// List<AdministrativoEntity> findByYyy(BigDecimal yyy);

	// List<AdministrativoEntity> findByXxxContainingAndYyy(String xxx, BigDecimal
	// yyy);

	@Query("SELECT a FROM AdministrativoEntity a LEFT JOIN FETCH a.persona p LEFT JOIN FETCH p.ubicacion LEFT JOIN FETCH p.genero LEFT JOIN FETCH a.estado LEFT JOIN FETCH a.cargo")
	List<AdministrativoEntity> findAllWithRelations();

	@Query("SELECT a FROM AdministrativoEntity a LEFT JOIN FETCH a.persona p LEFT JOIN FETCH p.ubicacion LEFT JOIN FETCH p.genero LEFT JOIN FETCH a.estado LEFT JOIN FETCH a.cargo WHERE a.id = :id")
	Optional<AdministrativoEntity> findByIdWithRelations(@Param("id") Integer id);
}
