/*
 * Created on 2026-05-01 ( 13:45:53 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.AspiranteEntity;

@Repository
public interface AspiranteRepository extends JpaRepository<AspiranteEntity, Integer> {

	@Query("SELECT a FROM AspiranteEntity a LEFT JOIN FETCH a.persona p LEFT JOIN FETCH p.ubicacion LEFT JOIN FETCH p.genero")
	List<AspiranteEntity> findAllWithRelations();

	@Query("SELECT a FROM AspiranteEntity a LEFT JOIN FETCH a.persona p LEFT JOIN FETCH p.ubicacion LEFT JOIN FETCH p.genero WHERE a.id = :id")
	Optional<AspiranteEntity> findByIdWithRelations(@Param("id") Integer id);
}