/*
 * Created on 2026-05-01 ( 13:45:54 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.CambiodocumentoEntity;

@Repository
public interface CambiodocumentoRepository extends JpaRepository<CambiodocumentoEntity, Integer> {

	@Query("SELECT c FROM CambiodocumentoEntity c LEFT JOIN FETCH c.documento LEFT JOIN FETCH c.documento2")
	List<CambiodocumentoEntity> findAllWithRelations();

	@Query("SELECT c FROM CambiodocumentoEntity c LEFT JOIN FETCH c.documento LEFT JOIN FETCH c.documento2 WHERE c.id = :id")
	Optional<CambiodocumentoEntity> findByIdWithRelations(@Param("id") Integer id);
}