/*
 * Created on 2026-05-01 ( 13:45:54 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.CargoEntity;

@Repository
public interface CargoRepository extends JpaRepository<CargoEntity, Integer> {

	@Query("SELECT c FROM CargoEntity c LEFT JOIN FETCH c.programa")
	List<CargoEntity> findAllWithRelations();

	@Query("SELECT c FROM CargoEntity c LEFT JOIN FETCH c.programa WHERE c.id = :id")
	Optional<CargoEntity> findByIdWithRelations(@Param("id") Integer id);
}