/*
 * Created on 2026-05-01 ( 13:45:55 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.CohorteEntity;

@Repository
public interface CohorteRepository extends JpaRepository<CohorteEntity, Integer> {

	@Query("SELECT c FROM CohorteEntity c LEFT JOIN FETCH c.estado")
	List<CohorteEntity> findAllWithRelations();

	@Query("SELECT c FROM CohorteEntity c LEFT JOIN FETCH c.estado WHERE c.id = :id")
	Optional<CohorteEntity> findByIdWithRelations(@Param("id") Integer id);
}