/*
 * Created on 2026-05-01 ( 13:45:55 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.DepartamentoEntity;

@Repository
public interface DepartamentoRepository extends JpaRepository<DepartamentoEntity, Integer> {

	@Query("SELECT d FROM DepartamentoEntity d LEFT JOIN FETCH d.pais")
	List<DepartamentoEntity> findAllWithRelations();

	@Query("SELECT d FROM DepartamentoEntity d LEFT JOIN FETCH d.pais WHERE d.id = :id")
	Optional<DepartamentoEntity> findByIdWithRelations(@Param("id") Integer id);
}