/*
 * Created on 2026-05-01 ( 13:45:55 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.DocumentoEntity;

@Repository
public interface DocumentoRepository extends JpaRepository<DocumentoEntity, Integer> {

	@Query("""
			SELECT d FROM DocumentoEntity d
			LEFT JOIN FETCH d.plazo
			LEFT JOIN FETCH d.tipodocumento
			LEFT JOIN FETCH d.estadodocumento
			LEFT JOIN FETCH d.administrativo
			LEFT JOIN FETCH d.aspirante
			""")
	List<DocumentoEntity> findAllWithRelations();

	@Query("""
			SELECT d FROM DocumentoEntity d
			LEFT JOIN FETCH d.plazo
			LEFT JOIN FETCH d.tipodocumento
			LEFT JOIN FETCH d.estadodocumento
			LEFT JOIN FETCH d.administrativo
			LEFT JOIN FETCH d.aspirante
			WHERE d.id = :id
			""")
	Optional<DocumentoEntity> findByIdWithRelations(@Param("id") Integer id);
}