/*
 * Created on 2026-05-06 ( 00:58:50 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.EntrevistadoresEntity;

/**
 * Spring Data JPA repository for the EntrevistadoresEntity entity.
 *
 * This interface extends {@link JpaRepository}, so it automatically inherits
 * standard persistence operations, including:
 * <ul>
 *   <li> Create/update entities: {@link JpaRepository#save(Object)} and {@link JpaRepository#saveAll(Iterable)}</li>
 *   <li> Basic queries: {@link JpaRepository#findById(Object)}, {@link JpaRepository#findAll()}, and {@link JpaRepository#getReferenceById(Object)}</li>
 *   <li> Validation and counting: {@link JpaRepository#existsById(Object)} and {@link JpaRepository#count()}</li>
 *   <li> Deletion: {@link JpaRepository#deleteById(Object)}, {@link JpaRepository#delete(Object)}, and {@link JpaRepository#deleteAll()}</li>
 *   <li> Paging and sorting: {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Pageable)}
 *     and {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Sort)}</li>
 * </ul>
 *
 * It can also be extended with derived query methods (findBy...),
 * following Spring Data JPA conventions.
 *
 * @category Repository
 * @version 1.0.0
 * @see JpaRepository
 * @see org.springframework.data.repository.CrudRepository
 * @see org.springframework.data.repository.PagingAndSortingRepository
 * @author a-cubica-r
 *
 */
@Repository
public interface EntrevistadoresRepository extends JpaRepository<EntrevistadoresEntity, Integer> {

	// Insert specific finders here 

	//List<EntrevistadoresEntity> findByXxx(String xxx);

	//List<EntrevistadoresEntity> findByXxxStartingWith(String xxx);

	//List<EntrevistadoresEntity> findByXxxContaining(String xxx);

	//List<EntrevistadoresEntity> findByYyy(BigDecimal yyy);

	//List<EntrevistadoresEntity> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);

	@Query("SELECT e FROM EntrevistadoresEntity e LEFT JOIN FETCH e.entrevista LEFT JOIN FETCH e.administrativo")
	List<EntrevistadoresEntity> findAllWithRelations();

	@Query("SELECT e FROM EntrevistadoresEntity e LEFT JOIN FETCH e.entrevista LEFT JOIN FETCH e.administrativo WHERE e.id = :id")
	Optional<EntrevistadoresEntity> findByIdWithRelations(@Param("id") Integer id);

	@Modifying
    @Query("DELETE FROM EntrevistadoresEntity e WHERE e.idEntrevista = :idEntrevista")
    void deleteByEntrevistaId(@Param("idEntrevista") Integer idEntrevista);
}
