/*
 * Created on 2026-05-06 ( 00:58:50 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.EntrevistadorEntity;

/**
 * Spring Data JPA repository for the EntrevistadorEntity entity.
 *
 * This interface extends {@link JpaRepository}, so it automatically inherits
 * standard persistence operations, including:
 * <ul>
 * <li>Create/update entities: {@link JpaRepository#save(Object)} and
 * {@link JpaRepository#saveAll(Iterable)}</li>
 * <li>Basic queries: {@link JpaRepository#findById(Object)},
 * {@link JpaRepository#findAll()}, and
 * {@link JpaRepository#getReferenceById(Object)}</li>
 * <li>Validation and counting: {@link JpaRepository#existsById(Object)} and
 * {@link JpaRepository#count()}</li>
 * <li>Deletion: {@link JpaRepository#deleteById(Object)},
 * {@link JpaRepository#delete(Object)}, and
 * {@link JpaRepository#deleteAll()}</li>
 * <li>Paging and sorting:
 * {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Pageable)}
 * and
 * {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Sort)}</li>
 * </ul>
 *
 * It can also be extended with derived query methods (findBy...),
 * following Spring Data JPA conventions.
 *
 * @category Repository
 * @version 1.0.0
 * @see JpaRepository
 * @see org.springframework.data.repository.CrudRepository
 * @see org.springframework.data.repository.PagingAndSortingRepository
 * @author a-cubica-r
 *
 */
@Repository
public interface EntrevistadorRepository extends JpaRepository<EntrevistadorEntity, Integer> {

	// Insert specific finders here

	// List<EntrevistadorEntity> findByXxx(String xxx);

	// List<EntrevistadorEntity> findByXxxStartingWith(String xxx);

	// List<EntrevistadorEntity> findByXxxContaining(String xxx);

	// List<EntrevistadorEntity> findByYyy(BigDecimal yyy);

	// List<EntrevistadorEntity> findByXxxContainingAndYyy(String xxx, BigDecimal
	// yyy);

	@Query("""
			SELECT ev FROM EntrevistadorEntity ev
			LEFT JOIN FETCH ev.administrativo a
			LEFT JOIN FETCH a.persona p
			LEFT JOIN FETCH p.genero
			LEFT JOIN FETCH a.estado
			LEFT JOIN FETCH a.cargo
			""")
	List<EntrevistadorEntity> findAllWithRelations();

	@Query("""
			SELECT ev FROM EntrevistadorEntity ev
			LEFT JOIN FETCH ev.administrativo a
			LEFT JOIN FETCH a.persona p
			LEFT JOIN FETCH p.genero
			LEFT JOIN FETCH a.estado
			LEFT JOIN FETCH a.cargo
			WHERE ev.id = :id
			""")
	Optional<EntrevistadorEntity> findByIdWithRelations(@Param("id") Integer id);
}
