/*
 * Created on 2026-05-06 ( 00:58:50 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.EntrevistaEntity;

/**
 * Spring Data JPA repository for the EntrevistaEntity entity.
 *
 * This interface extends {@link JpaRepository}, so it automatically inherits
 * standard persistence operations, including:
 * <ul>
 * <li>Create/update entities: {@link JpaRepository#save(Object)} and
 * {@link JpaRepository#saveAll(Iterable)}</li>
 * <li>Basic queries: {@link JpaRepository#findById(Object)},
 * {@link JpaRepository#findAll()}, and
 * {@link JpaRepository#getReferenceById(Object)}</li>
 * <li>Validation and counting: {@link JpaRepository#existsById(Object)} and
 * {@link JpaRepository#count()}</li>
 * <li>Deletion: {@link JpaRepository#deleteById(Object)},
 * {@link JpaRepository#delete(Object)}, and
 * {@link JpaRepository#deleteAll()}</li>
 * <li>Paging and sorting:
 * {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Pageable)}
 * and
 * {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Sort)}</li>
 * </ul>
 *
 * It can also be extended with derived query methods (findBy...),
 * following Spring Data JPA conventions.
 *
 * @category Repository
 * @version 1.0.0
 * @see JpaRepository
 * @see org.springframework.data.repository.CrudRepository
 * @see org.springframework.data.repository.PagingAndSortingRepository
 * @author a-cubica-r
 *
 */
@Repository
public interface EntrevistaRepository extends JpaRepository<EntrevistaEntity, Integer> {

    // Insert specific finders here

    // List<EntrevistaEntity> findByXxx(String xxx);

    // List<EntrevistaEntity> findByXxxStartingWith(String xxx);

    // List<EntrevistaEntity> findByXxxContaining(String xxx);

    // List<EntrevistaEntity> findByYyy(BigDecimal yyy);

    // List<EntrevistaEntity> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);

    @Query("""
            SELECT DISTINCT e FROM EntrevistaEntity e
            LEFT JOIN FETCH e.tipoentrevista
            LEFT JOIN FETCH e.entrevistador
            LEFT JOIN FETCH e.aspirante
            LEFT JOIN FETCH e.estado
            LEFT JOIN FETCH e.ubicacion
            """)
    List<EntrevistaEntity> findAllWithRelations();

    @Query("""
            SELECT e FROM EntrevistaEntity e
            LEFT JOIN FETCH e.tipoentrevista
            LEFT JOIN FETCH e.entrevistador
            LEFT JOIN FETCH e.aspirante
            LEFT JOIN FETCH e.estado
            LEFT JOIN FETCH e.ubicacion
            WHERE e.id = :id
            """)
    Optional<EntrevistaEntity> findByIdWithRelations(@Param("id") Integer id);

    @Modifying
    @Query("UPDATE EntrevistaEntity e SET e.calificacion = :calificacion WHERE e.id = :id")
    void updateCalificacion(@Param("id") Integer id, @Param("calificacion") float calificacion);
}
