/*
 * Created on 2026-05-01 ( 13:45:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.FacultadEntity;

@Repository
public interface FacultadRepository extends JpaRepository<FacultadEntity, Integer> {

	@Query("SELECT f FROM FacultadEntity f LEFT JOIN FETCH f.administrativo")
	List<FacultadEntity> findAllWithRelations();

	@Query("SELECT f FROM FacultadEntity f LEFT JOIN FETCH f.administrativo WHERE f.id = :id")
	Optional<FacultadEntity> findByIdWithRelations(@Param("id") Integer id);
}