/*
 * Created on 2026-05-01 ( 13:45:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.MunicipioEntity;

@Repository
public interface MunicipioRepository extends JpaRepository<MunicipioEntity, Integer> {

	@Query("SELECT m FROM MunicipioEntity m LEFT JOIN FETCH m.departamento")
	List<MunicipioEntity> findAllWithRelations();

	@Query("SELECT m FROM MunicipioEntity m LEFT JOIN FETCH m.departamento WHERE m.id = :id")
	Optional<MunicipioEntity> findByIdWithRelations(@Param("id") Integer id);
}