/*
 * Created on 2026-05-01 ( 13:45:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.OfertaacademicaEntity;

@Repository
public interface OfertaacademicaRepository extends JpaRepository<OfertaacademicaEntity, Integer> {

	@Query("""
			SELECT o FROM OfertaacademicaEntity o
			LEFT JOIN FETCH o.programa
			LEFT JOIN FETCH o.modalidad
			LEFT JOIN FETCH o.jornada
			LEFT JOIN FETCH o.cohorte
			LEFT JOIN FETCH o.plazo
			""")
	List<OfertaacademicaEntity> findAllWithRelations();

	@Query("""
			SELECT o FROM OfertaacademicaEntity o
			LEFT JOIN FETCH o.programa
			LEFT JOIN FETCH o.modalidad
			LEFT JOIN FETCH o.jornada
			LEFT JOIN FETCH o.cohorte
			LEFT JOIN FETCH o.plazo
			WHERE o.id = :id
			""")
	Optional<OfertaacademicaEntity> findByIdWithRelations(@Param("id") Integer id);
}