/*
 * Created on 2026-05-01 ( 13:45:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.PlazoEntity;

@Repository
public interface PlazoRepository extends JpaRepository<PlazoEntity, Integer> {

	@Query("SELECT p FROM PlazoEntity p LEFT JOIN FETCH p.tipoplazo")
	List<PlazoEntity> findAllWithRelations();

	@Query("SELECT p FROM PlazoEntity p LEFT JOIN FETCH p.tipoplazo WHERE p.id = :id")
	Optional<PlazoEntity> findByIdWithRelations(@Param("id") Integer id);
}