/*
 * Created on 2026-05-01 ( 13:45:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.ProgramaEntity;

@Repository
public interface ProgramaRepository extends JpaRepository<ProgramaEntity, Integer> {

	List<ProgramaEntity> findByIdFacultad(int idFacultad);

	@Query("""
			SELECT p FROM ProgramaEntity p
			LEFT JOIN FETCH p.sede
			LEFT JOIN FETCH p.administrativo
			LEFT JOIN FETCH p.facultad
			LEFT JOIN FETCH p.otrosvalores
			""")
	List<ProgramaEntity> findAllWithRelations();

	@Query("""
			SELECT p FROM ProgramaEntity p
			LEFT JOIN FETCH p.sede
			LEFT JOIN FETCH p.administrativo
			LEFT JOIN FETCH p.facultad
			LEFT JOIN FETCH p.otrosvalores
			WHERE p.id = :id
			""")
	Optional<ProgramaEntity> findByIdWithRelations(@Param("id") Integer id);
}