/*
 * Created on 2026-05-01 ( 13:45:59 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.SedeEntity;

@Repository
public interface SedeRepository extends JpaRepository<SedeEntity, Integer> {

	@Query("SELECT s FROM SedeEntity s LEFT JOIN FETCH s.ubicacion")
	List<SedeEntity> findAllWithRelations();

	@Query("SELECT s FROM SedeEntity s LEFT JOIN FETCH s.ubicacion WHERE s.id = :id")
	Optional<SedeEntity> findByIdWithRelations(@Param("id") Integer id);
}