/*
 * Created on 2026-05-01 ( 13:45:59 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.UbicacionEntity;

@Repository
public interface UbicacionRepository extends JpaRepository<UbicacionEntity, Integer> {

	@Query("SELECT u FROM UbicacionEntity u LEFT JOIN FETCH u.municipio")
	List<UbicacionEntity> findAllWithRelations();

	@Query("SELECT u FROM UbicacionEntity u LEFT JOIN FETCH u.municipio WHERE u.id = :id")
	Optional<UbicacionEntity> findByIdWithRelations(@Param("id") Integer id);
}