/*
 * Created on 2026-05-01 ( 13:45:59 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.UsuarioEntity;

@Repository
public interface UsuarioRepository extends JpaRepository<UsuarioEntity, Integer> {

	@Query("SELECT u FROM UsuarioEntity u LEFT JOIN FETCH u.rol LEFT JOIN FETCH u.clave WHERE u.nombreusuario = :nombreusuario")
	Optional<UsuarioEntity> findByNombreusuario(@Param("nombreusuario") String nombreusuario);

	@Query("SELECT u FROM UsuarioEntity u LEFT JOIN FETCH u.rol LEFT JOIN FETCH u.clave LEFT JOIN FETCH u.persona")
	List<UsuarioEntity> findAllWithRelations();

	@Query("SELECT u FROM UsuarioEntity u LEFT JOIN FETCH u.rol LEFT JOIN FETCH u.clave LEFT JOIN FETCH u.persona WHERE u.id = :id")
	Optional<UsuarioEntity> findByIdWithRelations(@Param("id") Integer id);
}