/*
 * Created on 2026-05-01 ( 13:45:55 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.time.LocalDate;

/**
 * DTO class for "Documento"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class DocumentoDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private LocalDate fechacargue ;
    private Integer idEstadodocumento ;
    private Integer idTipodocumento ;
    private Integer idAdministrativo ;
    private Integer idPlazo ;
    private Integer idAspirante ;
    private String enlaceurl ;
    private String keyfile ;
    private String observaciones ;
    //--- LINKS ( RELATIONSHIPS )
    private PlazoDTO plazo ; 
    private TipodocumentoDTO tipodocumento ; 
    private EstadodocumentoDTO estadodocumento ; 
    private AdministrativoDTO administrativo ; 
    private AspiranteDTO aspirante ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Documento[");
		sb.append("id=").append(id);
		sb.append(separator).append("fechacargue=").append(fechacargue);
		sb.append(separator).append("idEstadodocumento=").append(idEstadodocumento);
		sb.append(separator).append("idTipodocumento=").append(idTipodocumento);
		sb.append(separator).append("idAdministrativo=").append(idAdministrativo);
		sb.append(separator).append("idPlazo=").append(idPlazo);
		sb.append(separator).append("idAspirante=").append(idAspirante);
		// attribute 'enlaceurl' (type String) not usable in toString() 
		sb.append(separator).append("keyfile=").append(keyfile);
		// attribute 'observaciones' (type String) not usable in toString() 
		sb.append("]");
		return sb.toString();
	}
}
