/*
 * Created on 2026-05-06 ( 00:58:49 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

/**
 * DTO class for "Entrevista"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EntrevistaDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private LocalDate fecha ;
    private float calificacion ;
    private LocalTime tiempo ;
    private Integer idTipoentrevista ;
    private Integer idEntrevistador ;
    private Integer idAspirante ;
    private Integer idEstado ;
    private Integer idUbicacion ;
    //--- LINKS ( RELATIONSHIPS )
    private TipoentrevistaDTO tipoentrevista ; 
    private EntrevistadorDTO entrevistador ; 
    private AspiranteDTO aspirante ; 
    private EstadoDTO estado ; 
    private UbicacionDTO ubicacion ; 
    private List<EntrevistadoresDTO> entrevistadoresList ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Entrevista[");
		sb.append("id=").append(id);
		sb.append(separator).append("fecha=").append(fecha);
		sb.append(separator).append("calificacion=").append(calificacion);
		sb.append(separator).append("tiempo=").append(tiempo);
		sb.append(separator).append("idTipoentrevista=").append(idTipoentrevista);
		sb.append(separator).append("idEntrevistador=").append(idEntrevistador);
		sb.append(separator).append("idAspirante=").append(idAspirante);
		sb.append(separator).append("idEstado=").append(idEstado);
		sb.append(separator).append("idUbicacion=").append(idUbicacion);
		sb.append("]");
		return sb.toString();
	}
}
