/*
 * Created on 2026-05-06 ( 00:58:50 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * DTO class for "Entrevistador"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EntrevistadorDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private Integer idAdministrativo ;
    private String observaciones ;
    //--- LINKS ( RELATIONSHIPS )
    private AdministrativoDTO administrativo ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Entrevistador[");
		sb.append("id=").append(id);
		sb.append(separator).append("idAdministrativo=").append(idAdministrativo);
		// attribute 'observaciones' (type String) not usable in toString() 
		sb.append("]");
		return sb.toString();
	}
}
