/*
 * Created on 2026-05-01 ( 13:45:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * DTO class for "Facultad"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class FacultadDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private String nombre ;
    private String correo ;
    private Integer idAdministrativo ;
    //--- LINKS ( RELATIONSHIPS )
    private AdministrativoDTO administrativo ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Facultad[");
		sb.append("id=").append(id);
		sb.append(separator).append("nombre=").append(nombre);
		sb.append(separator).append("correo=").append(correo);
		sb.append(separator).append("idAdministrativo=").append(idAdministrativo);
		sb.append("]");
		return sb.toString();
	}
}
