/*
 * Created on 2026-05-01 ( 13:45:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * DTO class for "Ofertaacademica"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class OfertaacademicaDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private String encuentros ;
    private Integer cupos ;
    private Integer idPrograma ;
    private Integer idModalidad ;
    private Integer idJornada ;
    private Integer idCohorte ;
    private Integer idPlazo ;
    //--- LINKS ( RELATIONSHIPS )
    private ProgramaDTO programa ; 
    private ModalidadDTO modalidad ; 
    private JornadaDTO jornada ; 
    private CohorteDTO cohorte ; 
    private PlazoDTO plazo ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Ofertaacademica[");
		sb.append("id=").append(id);
		// attribute 'encuentros' (type String) not usable in toString() 
		sb.append(separator).append("cupos=").append(cupos);
		sb.append(separator).append("idPrograma=").append(idPrograma);
		sb.append(separator).append("idModalidad=").append(idModalidad);
		sb.append(separator).append("idJornada=").append(idJornada);
		sb.append(separator).append("idCohorte=").append(idCohorte);
		sb.append(separator).append("idPlazo=").append(idPlazo);
		sb.append("]");
		return sb.toString();
	}
}
