/*
 * Created on 2026-05-01 ( 13:45:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * DTO class for "Otrosvalores"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class OtrosvaloresDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private boolean carnet ;
    private boolean estampilla ;
    private boolean seguro ;

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Otrosvalores[");
		sb.append("id=").append(id);
		sb.append(separator).append("carnet=").append(carnet);
		sb.append(separator).append("estampilla=").append(estampilla);
		sb.append(separator).append("seguro=").append(seguro);
		sb.append("]");
		return sb.toString();
	}
}
