/*
 * Created on 2026-05-01 ( 13:45:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.time.LocalDate;

/**
 * DTO class for "Plazo"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PlazoDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private LocalDate fechainicio ;
    private LocalDate fechafin ;
    private Integer idTipoplazo ;
    //--- LINKS ( RELATIONSHIPS )
    private TipoplazoDTO tipoplazo ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Plazo[");
		sb.append("id=").append(id);
		sb.append(separator).append("fechainicio=").append(fechainicio);
		sb.append(separator).append("fechafin=").append(fechafin);
		sb.append(separator).append("idTipoplazo=").append(idTipoplazo);
		sb.append("]");
		return sb.toString();
	}
}
