/*
 * Created on 2026-05-01 ( 13:45:59 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * DTO class for "Usuario"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UsuarioDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private String nombreusuario ;
    private Integer idPersona ;
    private Integer idRol ;
    private Integer idClave ;
    //--- LINKS ( RELATIONSHIPS )
    private PersonaDTO persona ; 
    private RolDTO rol ; 
    private ClaveDTO clave ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Usuario[");
		sb.append("id=").append(id);
		sb.append(separator).append("nombreusuario=").append(nombreusuario);
		sb.append(separator).append("idPersona=").append(idPersona);
		sb.append(separator).append("idRol=").append(idRol);
		sb.append(separator).append("idClave=").append(idClave);
		sb.append("]");
		return sb.toString();
	}
}
