/*
 * Created on 2026-05-01 ( 13:45:53 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


/**
 * JPA entity class for "Cambiodocumento"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "cambiodocumento")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CambiodocumentoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS
    @Column(name="id_documentoanterior", nullable=false)
    private Integer        idDocumentoanterior ;

    @Column(name="id_documentoactual", nullable=false)
    private Integer        idDocumentoactual ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="id_documentoanterior", referencedColumnName="id", insertable=false, updatable=false)
    private DocumentoEntity  documento ;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="id_documentoactual", referencedColumnName="id", insertable=false, updatable=false)
    private DocumentoEntity  documento2 ;

}