/*
 * Created on 2026-05-01 ( 13:45:54 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


/**
 * JPA entity class for "Clave"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "clave")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ClaveEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS
    @Column(name="valor", nullable=false, length=65535)
    private String     valor ;

}