/*
 * Created on 2026-05-01 ( 13:45:55 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDate;


/**
 * JPA entity class for "Cohorte"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "cohorte")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CohorteEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS
    @Column(name="nombre", nullable=false, length=100)
    private String     nombre ;

    @Column(name="id_estado", nullable=false)
    private Integer        idEstado ;

    @Column(name="fecha_inicio", nullable=false)
    private LocalDate  fechaInicio ;

    @Column(name="fecha_fin", nullable=false)
    private LocalDate  fechaFin ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="id_estado", referencedColumnName="id", insertable=false, updatable=false)
    private EstadoEntity     estado ;

}