/*
 * Created on 2026-05-01 ( 13:45:55 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDate;


/**
 * JPA entity class for "Documento"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "documento")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DocumentoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS
    @Column(name="fechacargue", nullable=false)
    private LocalDate  fechacargue ;

    @Column(name="id_estadodocumento", nullable=false)
    private Integer        idEstadodocumento ;

    @Column(name="id_tipodocumento", nullable=false)
    private Integer        idTipodocumento ;

    @Column(name="id_administrativo")
    private Integer    idAdministrativo ;

    @Column(name="id_plazo", nullable=true)
    private Integer        idPlazo ;

    @Column(name="id_aspirante", nullable=true)
    private Integer        idAspirante ;

    @Column(name="enlaceurl", nullable=false, length=65535)
    private String     enlaceurl ;

    @Column(name="keyfile", nullable=false, length=255)
    private String     keyfile ;

    @Column(name="observaciones", length=65535)
    private String     observaciones ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="id_plazo", referencedColumnName="id", insertable=false, updatable=false)
    private PlazoEntity      plazo ;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="id_tipodocumento", referencedColumnName="id", insertable=false, updatable=false)
    private TipodocumentoEntity tipodocumento ;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="id_estadodocumento", referencedColumnName="id", insertable=false, updatable=false)
    private EstadodocumentoEntity estadodocumento ;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="id_administrativo", referencedColumnName="id", insertable=false, updatable=false)
    private AdministrativoEntity administrativo ;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="id_aspirante", referencedColumnName="id", insertable=false, updatable=false)
    private AspiranteEntity  aspirante ;

}