/*
 * Created on 2026-05-06 ( 00:58:50 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


/**
 * JPA entity class for "Entrevistadores"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "entrevistadores")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class EntrevistadoresEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS
    @Column(name="id_entrevista", nullable=false)
    private Integer        idEntrevista ;

    @Column(name="id_administrativo", nullable=false)
    private Integer        idAdministrativo ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="id_entrevista", referencedColumnName="id", insertable=false, updatable=false)
    private EntrevistaEntity entrevista ;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="id_administrativo", referencedColumnName="id", insertable=false, updatable=false)
    private AdministrativoEntity administrativo ;

}