/*
 * Created on 2026-05-01 ( 13:45:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDate;


/**
 * JPA entity class for "Persona"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "persona")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PersonaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS
    @Column(name="nombres", nullable=false, length=100)
    private String     nombres ;

    @Column(name="apellidos", nullable=false, length=100)
    private String     apellidos ;

    @Column(name="correo", nullable=false, length=100)
    private String     correo ;

    @Column(name="fechanacimiento", nullable=false)
    private LocalDate  fechanacimiento ;

    @Column(name="celular", nullable=false, length=12)
    private String     celular ;

    @Column(name="telefono", length=12)
    private String     telefono ;

    @Column(name="id_ubicacion", nullable=false)
    private Integer        idUbicacion ;

    @Column(name="id_genero", nullable=false)
    private Integer        idGenero ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="id_ubicacion", referencedColumnName="id", insertable=false, updatable=false)
    private UbicacionEntity  ubicacion ;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="id_genero", referencedColumnName="id", insertable=false, updatable=false)
    private GeneroEntity     genero ;

}