/*
 * Created on 2026-05-01 ( 13:45:59 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


/**
 * JPA entity class for "Tipodocumento"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tipodocumento")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TipodocumentoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS
    @Column(name="nombre", nullable=false, length=100)
    private String     nombre ;

    @Column(name="descripcion", length=65535)
    private String     descripcion ;

    @Column(name="extension", nullable=false, length=50)
    private String     extension ;

    @Column(name="tamanomaximo", nullable=false)
    private Integer        tamanomaximo ;

}