/*
 * Created on 2026-05-01 ( 13:45:53 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.AdministrativoEntity;
import ufps.edu.co.persistence.repositories.AdministrativoRepository;
import ufps.edu.co.rest.dto.AdministrativoDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Administrativo" <br>
 * 
 * @author Telosys
 */
@Service
@Transactional
public class AdministrativoService extends GenericService<AdministrativoEntity, AdministrativoDTO> {

    @Autowired
    private AdministrativoRepository repository;

    public AdministrativoService() {
        super(AdministrativoEntity.class, AdministrativoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<AdministrativoDTO> findAll() {
        return entityListToDtoList(repository.findAllWithRelations());
    }

    @Transactional(readOnly = true)
    public AdministrativoDTO findById(Integer id) {
        return entityToDto(repository.findByIdWithRelations(id));
    }

    public AdministrativoDTO create(AdministrativoDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public AdministrativoDTO update(Integer id, AdministrativoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Administrativo no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("...no encontrado con id: " + id);
        }
        repository.deleteById(id); // SELECT + DELETE (inevitable en Spring Data sin @Query)
    }

}