/*
 * Created on 2026-05-01 ( 13:45:53 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.AspiranteEntity;
import ufps.edu.co.persistence.repositories.AspiranteRepository;
import ufps.edu.co.rest.dto.AspiranteDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Aspirante" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class AspiranteService extends GenericService<AspiranteEntity, AspiranteDTO> {

    @Autowired
    private AspiranteRepository repository;

    public AspiranteService() {
        super(AspiranteEntity.class, AspiranteDTO.class);
    }

    @Transactional(readOnly = true)
    public List<AspiranteDTO> findAll() {
        return entityListToDtoList(repository.findAllWithRelations());
    }

    @Transactional(readOnly = true)
    public AspiranteDTO findById(Integer id) {
        return entityToDto(repository.findByIdWithRelations(id));
    }

    public AspiranteDTO create(AspiranteDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public AspiranteDTO update(Integer id, AspiranteDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Aspirante no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Aspirante no encontrado con id: " + id));
        repository.deleteById(id);
    }
}