/*
 * Created on 2026-05-01 ( 13:45:54 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.CambiodocumentoEntity;
import ufps.edu.co.persistence.repositories.CambiodocumentoRepository;
import ufps.edu.co.rest.dto.CambiodocumentoDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Cambiodocumento" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class CambiodocumentoService extends GenericService<CambiodocumentoEntity, CambiodocumentoDTO> {

    @Autowired
    private CambiodocumentoRepository repository;

    public CambiodocumentoService() {
        super(CambiodocumentoEntity.class, CambiodocumentoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<CambiodocumentoDTO> findAll() {
        return entityListToDtoList(repository.findAllWithRelations());
    }

    @Transactional(readOnly = true)
    public CambiodocumentoDTO findById(Integer id) {
        return entityToDto(repository.findByIdWithRelations(id));
    }

    public CambiodocumentoDTO create(CambiodocumentoDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public CambiodocumentoDTO update(Integer id, CambiodocumentoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Cambiodocumento no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Cambiodocumento no encontrado con id: " + id));
        repository.deleteById(id);
    }
}