/*
 * Created on 2026-05-01 ( 13:45:54 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.CargoEntity;
import ufps.edu.co.persistence.repositories.CargoRepository;
import ufps.edu.co.rest.dto.CargoDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Cargo" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class CargoService extends GenericService<CargoEntity, CargoDTO> {

    @Autowired
    private CargoRepository repository;

    public CargoService() {
        super(CargoEntity.class, CargoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<CargoDTO> findAll() {
        return entityListToDtoList(repository.findAllWithRelations());
    }

    @Transactional(readOnly = true)
    public CargoDTO findById(Integer id) {
        return entityToDto(repository.findByIdWithRelations(id));
    }

    public CargoDTO create(CargoDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public CargoDTO update(Integer id, CargoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Cargo no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Cargo no encontrado con id: " + id));
        repository.deleteById(id);
    }
}