/*
 * Created on 2026-05-01 ( 13:45:54 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.ClaveEntity;
import ufps.edu.co.persistence.repositories.ClaveRepository;
import ufps.edu.co.rest.dto.ClaveDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Clave" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class ClaveService extends GenericService<ClaveEntity, ClaveDTO> {

    @Autowired
    private ClaveRepository repository;

    public ClaveService() {
        super(ClaveEntity.class, ClaveDTO.class);
    }

    @Transactional(readOnly = true)
    public List<ClaveDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public ClaveDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public ClaveDTO create(ClaveDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public ClaveDTO update(Integer id, ClaveDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Clave no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Clave no encontrado con id: " + id));
        repository.deleteById(id);
    }
}