/*
 * Created on 2026-05-01 ( 13:45:55 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.CohorteEntity;
import ufps.edu.co.persistence.repositories.CohorteRepository;
import ufps.edu.co.rest.dto.CohorteDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Cohorte" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class CohorteService extends GenericService<CohorteEntity, CohorteDTO> {

    @Autowired
    private CohorteRepository repository;

    public CohorteService() {
        super(CohorteEntity.class, CohorteDTO.class);
    }

    @Transactional(readOnly = true)
    public List<CohorteDTO> findAll() {
        return entityListToDtoList(repository.findAllWithRelations());
    }

    @Transactional(readOnly = true)
    public CohorteDTO findById(Integer id) {
        return entityToDto(repository.findByIdWithRelations(id));
    }

    public CohorteDTO create(CohorteDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public CohorteDTO update(Integer id, CohorteDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Cohorte no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Cohorte no encontrado con id: " + id));
        repository.deleteById(id);
    }
}