/*
 * Created on 2026-05-06 ( 00:58:50 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.EntrevistadorEntity;
import ufps.edu.co.persistence.repositories.EntrevistadorRepository;
import ufps.edu.co.rest.dto.EntrevistadorDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Entrevistador" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class EntrevistadorService extends GenericService<EntrevistadorEntity, EntrevistadorDTO> {

    @Autowired
    private EntrevistadorRepository repository;

    public EntrevistadorService() {
        super(EntrevistadorEntity.class, EntrevistadorDTO.class);
    }

    @Transactional(readOnly = true)
    public List<EntrevistadorDTO> findAll() {
        return entityListToDtoList(repository.findAllWithRelations());
    }

    @Transactional(readOnly = true)
    public EntrevistadorDTO findById(Integer id) {
        return entityToDto(repository.findByIdWithRelations(id));
    }

    public EntrevistadorDTO create(EntrevistadorDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public EntrevistadorDTO update(Integer id, EntrevistadorDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevistador no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevistador no encontrado con id: " + id));
        repository.deleteById(id);
    }
}