/*
 * Created on 2026-05-06 ( 00:58:50 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.EntrevistaEntity;
import ufps.edu.co.persistence.repositories.EntrevistaRepository;
import ufps.edu.co.rest.dto.EntrevistaDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Entrevista" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class EntrevistaService extends GenericService<EntrevistaEntity, EntrevistaDTO> {

    @Autowired
    private EntrevistaRepository repository;

    public EntrevistaService() {
        super(EntrevistaEntity.class, EntrevistaDTO.class);
    }

    @Transactional(readOnly = true)
    public List<EntrevistaDTO> findAll() {
        return entityListToDtoList(repository.findAllWithRelations());
    }

    @Transactional(readOnly = true)
    public EntrevistaDTO findById(Integer id) {
        return entityToDto(repository.findByIdWithRelations(id));
    }

    public EntrevistaDTO create(EntrevistaDTO dto) {
        EntrevistaEntity saved = repository.save(dtoToEntity(dto));
        return entityToDto(repository.findByIdWithRelations(saved.getId())
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrada tras crear")));
    }

    public EntrevistaDTO update(Integer id, EntrevistaDTO dto) {
        repository.findByIdWithRelations(id)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrada con id: " + id));
        dto.setId(id);
        repository.save(dtoToEntity(dto));
        return findById(id);
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrado con id: " + id));
        repository.deleteById(id);
    }

    @Transactional
    public EntrevistaDTO rateInterview(Integer id, float calificacion) {
        repository.updateCalificacion(id, calificacion);
        return findById(id);
    }
}