/*
 * Created on 2026-05-01 ( 13:45:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.EstadoEntity;
import ufps.edu.co.persistence.repositories.EstadoRepository;
import ufps.edu.co.rest.dto.EstadoDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Estado" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class EstadoService extends GenericService<EstadoEntity, EstadoDTO> {

    @Autowired
    private EstadoRepository repository;

    public EstadoService() {
        super(EstadoEntity.class, EstadoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<EstadoDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public EstadoDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public EstadoDTO create(EstadoDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public EstadoDTO update(Integer id, EstadoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Estado no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Estado no encontrado con id: " + id));
        repository.deleteById(id);
    }
}