/*
 * Created on 2026-05-01 ( 13:45:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.EstadodocumentoEntity;
import ufps.edu.co.persistence.repositories.EstadodocumentoRepository;
import ufps.edu.co.rest.dto.EstadodocumentoDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Estadodocumento" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class EstadodocumentoService extends GenericService<EstadodocumentoEntity, EstadodocumentoDTO> {

    @Autowired
    private EstadodocumentoRepository repository;

    public EstadodocumentoService() {
        super(EstadodocumentoEntity.class, EstadodocumentoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<EstadodocumentoDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public EstadodocumentoDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public EstadodocumentoDTO create(EstadodocumentoDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public EstadodocumentoDTO update(Integer id, EstadodocumentoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Estadodocumento no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Estadodocumento no encontrado con id: " + id));
        repository.deleteById(id);
    }
}