/*
 * Created on 2026-05-01 ( 13:45:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.FacultadEntity;
import ufps.edu.co.persistence.repositories.FacultadRepository;
import ufps.edu.co.rest.dto.FacultadDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Facultad" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class FacultadService extends GenericService<FacultadEntity, FacultadDTO> {

    @Autowired
    private FacultadRepository repository;

    public FacultadService() {
        super(FacultadEntity.class, FacultadDTO.class);
    }

    @Transactional(readOnly = true)
    public List<FacultadDTO> findAll() {
        return entityListToDtoList(repository.findAllWithRelations());
    }

    @Transactional(readOnly = true)
    public FacultadDTO findById(Integer id) {
        return entityToDto(repository.findByIdWithRelations(id));
    }

    public FacultadDTO create(FacultadDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public FacultadDTO update(Integer id, FacultadDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Facultad no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Facultad no encontrado con id: " + id));
        repository.deleteById(id);
    }
}