/*
 * Created on 2026-05-01 ( 13:45:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.GeneroEntity;
import ufps.edu.co.persistence.repositories.GeneroRepository;
import ufps.edu.co.rest.dto.GeneroDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Genero" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class GeneroService extends GenericService<GeneroEntity, GeneroDTO> {

    @Autowired
    private GeneroRepository repository;

    public GeneroService() {
        super(GeneroEntity.class, GeneroDTO.class);
    }

    @Transactional(readOnly = true)
    public List<GeneroDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public GeneroDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public GeneroDTO create(GeneroDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public GeneroDTO update(Integer id, GeneroDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Genero no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Genero no encontrado con id: " + id));
        repository.deleteById(id);
    }
}