/*
 * Created on 2026-05-01 ( 13:45:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.JornadaEntity;
import ufps.edu.co.persistence.repositories.JornadaRepository;
import ufps.edu.co.rest.dto.JornadaDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Jornada" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class JornadaService extends GenericService<JornadaEntity, JornadaDTO> {

    @Autowired
    private JornadaRepository repository;

    public JornadaService() {
        super(JornadaEntity.class, JornadaDTO.class);
    }

    @Transactional(readOnly = true)
    public List<JornadaDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public JornadaDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public JornadaDTO create(JornadaDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public JornadaDTO update(Integer id, JornadaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Jornada no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Jornada no encontrado con id: " + id));
        repository.deleteById(id);
    }
}