/*
 * Created on 2026-05-01 ( 13:45:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.ModalidadEntity;
import ufps.edu.co.persistence.repositories.ModalidadRepository;
import ufps.edu.co.rest.dto.ModalidadDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Modalidad" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class ModalidadService extends GenericService<ModalidadEntity, ModalidadDTO> {

    @Autowired
    private ModalidadRepository repository;

    public ModalidadService() {
        super(ModalidadEntity.class, ModalidadDTO.class);
    }

    @Transactional(readOnly = true)
    public List<ModalidadDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public ModalidadDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public ModalidadDTO create(ModalidadDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public ModalidadDTO update(Integer id, ModalidadDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Modalidad no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Modalidad no encontrado con id: " + id));
        repository.deleteById(id);
    }
}