/*
 * Created on 2026-05-01 ( 13:45:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.MunicipioEntity;
import ufps.edu.co.persistence.repositories.MunicipioRepository;
import ufps.edu.co.rest.dto.MunicipioDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Municipio" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class MunicipioService extends GenericService<MunicipioEntity, MunicipioDTO> {

    @Autowired
    private MunicipioRepository repository;

    public MunicipioService() {
        super(MunicipioEntity.class, MunicipioDTO.class);
    }

    @Transactional(readOnly = true)
    public List<MunicipioDTO> findAll() {
        return entityListToDtoList(repository.findAllWithRelations());
    }

    @Transactional(readOnly = true)
    public MunicipioDTO findById(Integer id) {
        return entityToDto(repository.findByIdWithRelations(id));
    }

    public MunicipioDTO create(MunicipioDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public MunicipioDTO update(Integer id, MunicipioDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Municipio no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Municipio no encontrado con id: " + id));
        repository.deleteById(id);
    }
}