/*
 * Created on 2026-05-01 ( 13:45:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.OfertaacademicaEntity;
import ufps.edu.co.persistence.repositories.OfertaacademicaRepository;
import ufps.edu.co.rest.dto.OfertaacademicaDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Ofertaacademica" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class OfertaacademicaService extends GenericService<OfertaacademicaEntity, OfertaacademicaDTO> {

    @Autowired
    private OfertaacademicaRepository repository;

    public OfertaacademicaService() {
        super(OfertaacademicaEntity.class, OfertaacademicaDTO.class);
    }

    @Transactional(readOnly = true)
    public List<OfertaacademicaDTO> findAll() {
        return entityListToDtoList(repository.findAllWithRelations());
    }

    @Transactional(readOnly = true)
    public OfertaacademicaDTO findById(Integer id) {
        return entityToDto(repository.findByIdWithRelations(id));
    }

    public OfertaacademicaDTO create(OfertaacademicaDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public OfertaacademicaDTO update(Integer id, OfertaacademicaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Ofertaacademica no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Ofertaacademica no encontrado con id: " + id));
        repository.deleteById(id);
    }
}