/*
 * Created on 2026-05-01 ( 13:45:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.OtrosvaloresEntity;
import ufps.edu.co.persistence.repositories.OtrosvaloresRepository;
import ufps.edu.co.rest.dto.OtrosvaloresDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Otrosvalores" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class OtrosvaloresService extends GenericService<OtrosvaloresEntity, OtrosvaloresDTO> {

    @Autowired
    private OtrosvaloresRepository repository;

    public OtrosvaloresService() {
        super(OtrosvaloresEntity.class, OtrosvaloresDTO.class);
    }

    @Transactional(readOnly = true)
    public List<OtrosvaloresDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public OtrosvaloresDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public OtrosvaloresDTO create(OtrosvaloresDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public OtrosvaloresDTO update(Integer id, OtrosvaloresDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Otrosvalores no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Otrosvalores no encontrado con id: " + id));
        repository.deleteById(id);
    }
}