/*
 * Created on 2026-05-01 ( 13:45:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.PlazoEntity;
import ufps.edu.co.persistence.repositories.PlazoRepository;
import ufps.edu.co.rest.dto.PlazoDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Plazo" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class PlazoService extends GenericService<PlazoEntity, PlazoDTO> {

    @Autowired
    private PlazoRepository repository;

    public PlazoService() {
        super(PlazoEntity.class, PlazoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<PlazoDTO> findAll() {
        return entityListToDtoList(repository.findAllWithRelations());
    }

    @Transactional(readOnly = true)
    public PlazoDTO findById(Integer id) {
        return entityToDto(repository.findByIdWithRelations(id));
    }

    public PlazoDTO create(PlazoDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public PlazoDTO update(Integer id, PlazoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Plazo no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Plazo no encontrado con id: " + id));
        repository.deleteById(id);
    }
}