/*
 * Created on 2026-05-01 ( 13:45:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.ProgramaEntity;
import ufps.edu.co.persistence.repositories.ProgramaRepository;
import ufps.edu.co.rest.dto.ProgramaDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Programa" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class ProgramaService extends GenericService<ProgramaEntity, ProgramaDTO> {

    @Autowired
    private ProgramaRepository repository;

    public ProgramaService() {
        super(ProgramaEntity.class, ProgramaDTO.class);
    }

    @Transactional(readOnly = true)
    public List<ProgramaDTO> findAll() {
        return entityListToDtoList(repository.findAllWithRelations());
    }

    @Transactional(readOnly = true)
    public ProgramaDTO findById(Integer id) {
        return entityToDto(repository.findByIdWithRelations(id));
    }

    public ProgramaDTO create(ProgramaDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public ProgramaDTO update(Integer id, ProgramaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Programa no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Programa no encontrado con id: " + id));
        repository.deleteById(id);
    }

    public List<ProgramaDTO> findByIdFacultad(int idFacultad) {
        return entityListToDtoList(repository.findByIdFacultad(idFacultad));
    }
}