/*
 * Created on 2026-05-01 ( 13:45:59 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.RolEntity;
import ufps.edu.co.persistence.repositories.RolRepository;
import ufps.edu.co.rest.dto.RolDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Rol" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class RolService extends GenericService<RolEntity, RolDTO> {

    @Autowired
    private RolRepository repository;

    public RolService() {
        super(RolEntity.class, RolDTO.class);
    }

    @Transactional(readOnly = true)
    public List<RolDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public RolDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public RolDTO create(RolDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public RolDTO update(Integer id, RolDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Rol no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Rol no encontrado con id: " + id));
        repository.deleteById(id);
    }
}