/*
 * Created on 2026-05-01 ( 13:45:59 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.SedeEntity;
import ufps.edu.co.persistence.repositories.SedeRepository;
import ufps.edu.co.rest.dto.SedeDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Sede" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class SedeService extends GenericService<SedeEntity, SedeDTO> {

    @Autowired
    private SedeRepository repository;

    public SedeService() {
        super(SedeEntity.class, SedeDTO.class);
    }

    @Transactional(readOnly = true)
    public List<SedeDTO> findAll() {
        return entityListToDtoList(repository.findAllWithRelations());
    }

    @Transactional(readOnly = true)
    public SedeDTO findById(Integer id) {
        return entityToDto(repository.findByIdWithRelations(id));
    }

    public SedeDTO create(SedeDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public SedeDTO update(Integer id, SedeDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Sede no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Sede no encontrado con id: " + id));
        repository.deleteById(id);
    }
}