/*
 * Created on 2026-05-01 ( 13:45:59 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.TipoentrevistaEntity;
import ufps.edu.co.persistence.repositories.TipoentrevistaRepository;
import ufps.edu.co.rest.dto.TipoentrevistaDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Tipoentrevista" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class TipoentrevistaService extends GenericService<TipoentrevistaEntity, TipoentrevistaDTO> {

    @Autowired
    private TipoentrevistaRepository repository;

    public TipoentrevistaService() {
        super(TipoentrevistaEntity.class, TipoentrevistaDTO.class);
    }

    @Transactional(readOnly = true)
    public List<TipoentrevistaDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public TipoentrevistaDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public TipoentrevistaDTO create(TipoentrevistaDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public TipoentrevistaDTO update(Integer id, TipoentrevistaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Tipoentrevista no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Tipoentrevista no encontrado con id: " + id));
        repository.deleteById(id);
    }
}