/*
 * Created on 2026-05-01 ( 13:45:59 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.TipodocumentoEntity;
import ufps.edu.co.persistence.repositories.TipodocumentoRepository;
import ufps.edu.co.rest.dto.TipodocumentoDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Tipodocumento" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class TipodocumentoService extends GenericService<TipodocumentoEntity, TipodocumentoDTO> {

    @Autowired
    private TipodocumentoRepository repository;

    public TipodocumentoService() {
        super(TipodocumentoEntity.class, TipodocumentoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<TipodocumentoDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public TipodocumentoDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public TipodocumentoDTO create(TipodocumentoDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public TipodocumentoDTO update(Integer id, TipodocumentoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Tipodocumento no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Tipodocumento no encontrado con id: " + id));
        repository.deleteById(id);
    }
}