/*
 * Created on 2026-05-01 ( 13:45:59 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.TipoplazoEntity;
import ufps.edu.co.persistence.repositories.TipoplazoRepository;
import ufps.edu.co.rest.dto.TipoplazoDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Tipoplazo" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class TipoplazoService extends GenericService<TipoplazoEntity, TipoplazoDTO> {

    @Autowired
    private TipoplazoRepository repository;

    public TipoplazoService() {
        super(TipoplazoEntity.class, TipoplazoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<TipoplazoDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public TipoplazoDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public TipoplazoDTO create(TipoplazoDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public TipoplazoDTO update(Integer id, TipoplazoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Tipoplazo no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Tipoplazo no encontrado con id: " + id));
        repository.deleteById(id);
    }
}