/*
 * Created on 2026-05-01 ( 13:45:59 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.UbicacionEntity;
import ufps.edu.co.persistence.repositories.UbicacionRepository;
import ufps.edu.co.rest.dto.UbicacionDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Ubicacion" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class UbicacionService extends GenericService<UbicacionEntity, UbicacionDTO> {

    @Autowired
    private UbicacionRepository repository;

    public UbicacionService() {
        super(UbicacionEntity.class, UbicacionDTO.class);
    }

    @Transactional(readOnly = true)
    public List<UbicacionDTO> findAll() {
        return entityListToDtoList(repository.findAllWithRelations());
    }

    @Transactional(readOnly = true)
    public UbicacionDTO findById(Integer id) {
        return entityToDto(repository.findByIdWithRelations(id));
    }

    public UbicacionDTO create(UbicacionDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public UbicacionDTO update(Integer id, UbicacionDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Ubicacion no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Ubicacion no encontrado con id: " + id));
        repository.deleteById(id);
    }
}