/*
 * Created on 2026-05-01 ( 13:45:59 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.UsuarioEntity;
import ufps.edu.co.persistence.repositories.UsuarioRepository;
import ufps.edu.co.rest.dto.UsuarioDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Usuario" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class UsuarioService extends GenericService<UsuarioEntity, UsuarioDTO> {

    @Autowired
    private UsuarioRepository repository;

    public UsuarioService() {
        super(UsuarioEntity.class, UsuarioDTO.class);
    }

    @Transactional(readOnly = true)
    public List<UsuarioDTO> findAll() {
        return entityListToDtoList(repository.findAllWithRelations());
    }

    @Transactional(readOnly = true)
    public UsuarioDTO findById(Integer id) {
        return entityToDto(repository.findByIdWithRelations(id));
    }

    public UsuarioDTO create(UsuarioDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public UsuarioDTO update(Integer id, UsuarioDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Usuario no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Usuario no encontrado con id: " + id));
        repository.deleteById(id);
    }
}